name: Build Docker Images
run-name: Building ${{ github.ref_name }}
on: workflow_dispatch
jobs:
  Generate-Build-Tag:
    uses: ./.github/workflows/generate-build-tag.yml
  Build-and-Push-Docker-Images-to-ECR:
    strategy:
      matrix:
        deploymentEnvironment: [stg, prd]
    needs: Generate-Build-Tag
    uses: ./.github/workflows/build-image-single-env.yml
    with: 
      deploymentEnvironment: ${{ matrix.deploymentEnvironment }}
      buildTag: ${{ needs.Generate-Build-Tag.outputs.build-tag }}_${{ matrix.deploymentEnvironment }}
    secrets: inherit