name: Build Docker Images
run-name: ${{ github.actor }} is Building and Pushing Docker images to ECR
on: workflow_dispatch
jobs:
  Generate-Build-Tag:
    uses: ./.github/workflows/generate-build-tag.yml
  Build-and-Push-Docker-Images-to-ECR:
    strategy:
      matrix:
        deploymentEnvironment: [stg]
    uses: ./.github/workflows/build-image-single-env.yml
    with: 
      deploymentEnvironment: ${{ matrix.deploymentEnvironment }}
    secrets: inherit